version: '2'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    env_file:
      - ./test.env
    environment:
      - LANG=C.UTF-8
      - TERM=dumb
      - MYSQL_ROOT_PASSWORD=thoughtworks
      - MYSQL_DATABASE=BronzeSword
      - MYSQL_PASSWORD=12345678
      - MYSQL_USER=BronzeSword
    networks:
      main:
        aliases:
          - mysql
  paper-api:
    image: jetty:9.3
    volumes:
      - ../paper-api/build/libs:/var/lib/jetty/webapps
    ports:
      - "8080:8080"
    networks:
      main:
        aliases:
          - paper-api
  web-api:
    image: node:6.9.5
    ports:
      - "3000:3000"
    volumes:
      - ../web-api:/var/app
    command: bash -c "cd /var/app && export NODE_ENV=show-case && npm start"
    networks:
      main:
        aliases:
          - web-api
  mongo:
    image: mongo:3.2
    ports:
      - "27017:27017"
    networks:
      main:
        aliases:
          - mongo
  jenkins-dind:
    build: ./jenkins-docker
    env_file:
      - ./test.env
    ports:
      - "8088:8080"
    volumes:
      - ./jenkins/.ssh/id_rsa.pub:/var/jenkins_home/.ssh/id_rsa.pub
      - ./jenkins/.ssh/id_rsa:/var/jenkins_home/.ssh/id_rsa
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ./jenkins/.ssh/known_hosts:/var/jenkins_home/.ssh/known_hosts
    networks:
      main:
        aliases:
          - jenkins
  nginx:
    image: nginx:1.9
    ports:
      - "8888:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/files:/var/fs
      - ../web/public/assets:/var/twars/web
      - ../teacher-admin-web/public/assets:/var/twars/teacher-admin-web
    networks:
      main:
        aliases:
          - nginx
networks:
  main:
